complexity:
  script:
    - xenon --max-average A --max-modules B --max-absolute B .
  tags:
    - docker

flake8:
  script:
    - flake8 *
  tags:
    - docker

deploy_dev:
  stage: deploy
  environment: dev
  script:
    - docker build -t hellobink/pelops:dev .
    - docker login -u binkautomation -p epitome-generic-basilisk
    - docker push hellobink/pelops:dev
  only:
    - master
  tags:
    - shell

deploy_staging:
  stage: deploy
  environment: staging
  script:
    - docker build -t hellobink/pelops:staging .
    - docker login -u binkautomation -p epitome-generic-basilisk
    - docker push hellobink/pelops:staging
  only:
    - staging
  tags:
    - shell

deploy_production:
  stage: deploy
  environment: production
  script:
    - docker build -t hellobink/pelops:production .
    - docker login -u binkautomation -p epitome-generic-basilisk
    - docker push hellobink/pelops:production
  only:
    - production
  tags:
    - shell
