stages:
  - tests
  - build
  - tagging

complexity:
  stage: tests
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  stage: tests
  script:
    - flake8 *

build-develop:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/pelops:latest" .
    - docker push "$CI_REGISTRY/pelops:latest"
  only:
    - develop

tag-develop:
  stage: tagging
  image: binkops.azurecr.io/tagbot:latest
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_USER" --source "$CI_REGISTRY/pelops:latest" --tag "develop-$CI_COMMIT_SHORT_SHA"
  only:
    - develop

build-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build --pull -t "$CI_REGISTRY/pelops:$CI_COMMIT_TAG" .
    - docker push "$CI_REGISTRY/pelops:$CI_COMMIT_TAG"
  only:
    - tags

tag-staging:
  stage: tagging
  image: binkops.azurecr.io/tagbot:latest
  script:
    - tagbot --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_USER" --source "$CI_REGISTRY/pelops:$CI_COMMIT_TAG" --tag "staging-$CI_COMMIT_TAG"
  only:
    - tags
