stages:
  - tests
  - build

complexity:
  stage: tests
  image: binkhq/python:3.8
  before_script:
    - pip install xenon
  script:
    - xenon --max-average A --max-modules B --max-absolute B .

flake8:
  stage: tests
  image: binkhq/python:3.8
  before_script:
    - pip install flake8
  script:
    - flake8

build-develop:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="develop-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/pelops:$CTAG" .
    - docker push "$CI_REGISTRY/pelops:$CTAG"
  only:
    - develop

build-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export CTAG="staging-$(date +%F-%H%M%S)"
    - docker build --pull -t "$CI_REGISTRY/pelops:$CTAG" .
    - docker push "$CI_REGISTRY/pelops:$CTAG"
  only:
    - tags
