#!/usr/bin/with-contenv /bin/bash

if [ "$NGINX_LOG_ACCESS" = false ] ; then
  echo "WARNING: Nginx Access Logs are being discarded"
  ln -sf /dev/null /var/log/nginx/access.log
else
  ln -sf /dev/stdout /var/log/nginx/access.log
fi

if [ "$NGINX_LOG_ERROR" = false ] ; then
  echo "WARNING: Nginx Error Logs are being discarded"
  ln -sf /dev/null /var/log/nginx/error.log
else
  ln -sf /dev/stderr /var/log/nginx/error.log
fi

if [ "$UWSGI_LOG_ENABLED" = false ] ; then
  echo "WARNING: Uwsgi System Logs are being discarded"
  ln -sf /dev/null /var/log/uwsgi.log
else
  ln -sf /dev/stdout /var/log/uwsgi.log
fi
