name: test

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install poetry
      - run: poetry config virtualenvs.create false
      - run: poetry config http-basic.azure jeff ${{ secrets.AZURE_DEVOPS_PAT }}
      - run: poetry install
      - run: xenon --no-assert --max-average A --max-modules B --max-absolute B .
      - run: ruff format . --check
      - run: ruff check .
      - run: refurb .
      - run: mypy .
